name: multi_image
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: 0.6.4 # 图片选取（只能一张）
  flutter_screenutil: ^0.5.3  #屏幕适配
  fluttertoast: ^3.1.3  #吐司
  flutter_swiper: ^1.1.6  #轮播图效果
  dio: ^3.0.2 #网络请求框架
  flutter_easyrefresh: ^2.0.4 #下拉刷新
  webview_flutter: ^0.3.15+1  #WebView
  cookie_jar: ^1.0.0  # 和 dio 配套使用的 cookie 管理插件
  dio_cookie_manager: ^1.0.0  #latest version
  shared_preferences: ^0.5.3+4
  event_bus: ^1.1.0 # 事件监听
  url_launcher: ^5.4.2  #打开浏览器
  image_cropper: ^1.2.1    #图片剪切
  flare_flutter: ^1.7.1   #动画
  shimmer: ^1.0.1     # 微光效果控件
  flutter_html: ^0.9.6  #解析HTML字符串
  connectivity: 0.4.8+2 #监听网络状态
  provider: 4.0.4  # 状态管理
  package_info: 0.4.0+16 # 获得应用版本信息
  flutter_downloader: 1.4.2 # 下载文件
  path_provider: 1.6.5  #获得文件路径
  permission_handler: 5.0.0+hotfix.3  # 请求权限
  progress_dialog: 1.2.1  # 进度显示插件
  mobsms: ^1.1.0  # 验证码请求

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/flrs/
    - assets/img/btn_tongyong_n.jpg
    - assets/img/btn_tongyong_p.jpg
    - assets/img/ic_about.png
    - assets/img/ic_about_w.png
    - assets/img/ic_account_normal.png
    - assets/img/ic_add.png
    - assets/img/ic_article.png
    - assets/img/ic_back.png
    - assets/img/ic_back_b.png
    - assets/img/ic_book_normal.png
    - assets/img/ic_book_selected.png
    - assets/img/ic_bottom_bar_home.png
    - assets/img/ic_bottom_bar_mine.png
    - assets/img/ic_bottom_bar_navi.png
    - assets/img/ic_bottom_bar_project.png
    - assets/img/ic_bottom_bar_wechat.png
    - assets/img/ic_browser.png
    - assets/img/ic_browser_b.png
    - assets/img/ic_check_box_checked.png
    - assets/img/ic_check_box_unchecked.png
    - assets/img/ic_close.png
    - assets/img/ic_close_b.png
    - assets/img/ic_coin.png
    - assets/img/ic_collect.png
    - assets/img/ic_collect_b.png
    - assets/img/ic_copy_link.png
    - assets/img/ic_copy_link_b.png
    - assets/img/ic_delete.png
    - assets/img/ic_empty.png
    - assets/img/ic_error.png
    - assets/img/ic_exit.png
    - assets/img/ic_exit_b.png
    - assets/img/ic_eye_normal.png
    - assets/img/ic_favorite.png
    - assets/img/ic_github.png
    - assets/img/ic_heart.png
    - assets/img/ic_home.png
    - assets/img/ic_home_b.png
    - assets/img/ic_home_g.png
    - assets/img/ic_home_normal.png
    - assets/img/ic_home_selected.png
    - assets/img/ic_http_interrupt.png
    - assets/img/ic_http_interrupt_b.png
    - assets/img/ic_jianshu.png
    - assets/img/ic_launcher_foreground.png
    - assets/img/ic_launcher_round.png
    - assets/img/ic_menu.png
    - assets/img/ic_menu_b.png
    - assets/img/ic_mine_normal.png
    - assets/img/ic_mine_selected.png
    - assets/img/ic_more.png
    - assets/img/ic_next.png
    - assets/img/ic_password_normal.png
    - assets/img/ic_project_normal.png
    - assets/img/ic_project_selected.png
    - assets/img/ic_qq.png
    - assets/img/ic_qq_group.png
    - assets/img/ic_rank.png
    - assets/img/ic_rank_1.png
    - assets/img/ic_rank_2.png
    - assets/img/ic_rank_3.png
    - assets/img/ic_read_later.png
    - assets/img/ic_read_later_b.png
    - assets/img/ic_refresh.png
    - assets/img/ic_refresh_b.png
    - assets/img/ic_remove.png
    - assets/img/ic_right_b.png
    - assets/img/ic_right_g.png
    - assets/img/ic_rule.png
    - assets/img/ic_search.png
    - assets/img/ic_setting.png
    - assets/img/ic_share.png
    - assets/img/ic_share_b.png
    - assets/img/ic_swipe_back.png
    - assets/img/ic_swipe_back_b.png
    - assets/img/ic_wechat_normal.png
    - assets/img/ic_wechat_selected.png
    - assets/img/image_holder.png
    - assets/img/img_book.png
    - assets/img/img_github.png
    - assets/img/img_heart.png
    - assets/img/img_right.png
    - assets/img/img_setting.png
    - assets/img/img_star.png
    - assets/img/img_user_head.png
    - assets/img/login_bg.png
    - assets/img/logo.png
    - assets/img/pic_404.jpg
    - assets/img/zan_0.png
    - assets/img/zan_1.png
    - assets/img/mieba.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
